# Generated by Django 6.0.2 on 2026-03-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicelog',
            name='quality',
            field=models.CharField(choices=[('LOW', 'L'), ('MEDIUM', 'M'), ('DEEP', 'D')], default='MEDIUM', max_length=50),
        ),
    ]
