# Generated by Django 6.0.2 on 2026-03-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_practicelog_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicelog',
            name='post_practice_retention',
            field=models.IntegerField(default=100, help_text='Retention % immediately after this practice'),
        ),
        migrations.AlterField(
            model_name='practicelog',
            name='quality',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('DEEP', 'Deep')], default='MEDIUM', max_length=50),
        ),
    ]
